### PR TITLE
[FEATURE] Add Jenkins pipeline script

### PR DESCRIPTION
**Pull request by rrahn**
please review!

Adds a '.jenkinsfile' file to trigger continuous integration and continuous delivery pipeline.
The pipeline will remove the separate CI tests currently running on Jenkins.

@marehr @h-2 please review

### CODE REVIEW

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by rrahn** [comment]
!test

**Comment by h-2** [comment]
Like I said, I would prefer if either all things run on unix are called unix, or none (maybe easier). Otherwise it is inconsistent and every person would ask themselves "What OS is performance being tested on?"

**Comment by rrahn** [comment]
Ok, I removed the unix for now. We can later on adapt this, when we have macOS and Win builds for the unit tests. The continuous delivery pipeline is also setup. From now on, we publish the latest stable release on http://packages.seqan.de

**Pull request merged**
