### PR TITLE
[FIX] prev_last_active_cell does not need special attention on score_mask

### PR DESCRIPTION
**Pull request by marehr**
It turns out that we don't need this case.

### CODE REVIEW

**Comment by marehr** [comment]
> LGTM, but is this a consequence of another PR?
> When we introduced this change, it actually fixed something IIRC.

Yes and no. I figured out that the change fixed a bug, but then later discovered that the bug was in a completely different part. The `advance_score` call turned out to be wrong, because in some situations in/decreased the actual score to a value which was wrong.

**Comment by smehringer** [comment]
> Yes and no. I figured out that the change fixed a bug, but then later discovered that the bug was in a completely different part. The advance_score call turned out to be wrong, because in some situations in/decreased the actual score to a value which was wrong.

Can you maybe reference this fix you mention within this PR's commit message?

**Comment by rrahn** [comment]
>Can you maybe reference this fix you mention within this PR's commit message?

I guess, this is more like an internal thing not reported as a bug or related to any ticket except some general implement edit distance algorithm. In general I am also in favor of having an issue for every PR but in the current state of the project I find it not very practical.

**Comment by rrahn** [comment]
But of course @marehr if you have a ticket for this please add it but I guess this can be merged anyway.

**Pull request merged**
