### PR TITLE
pull changes from release-3.0.2 into master - progress of week 01

### PR DESCRIPTION
**Pull request by marehr**
Merge current progress from release-3.0.2 into master branch.

### CODE REVIEW

**Comment by smehringer** [comment]
travis fails?

**Comment by marehr** [comment]
I'm investigating.

**Comment by marehr** [comment]
Okay I found it. 

Failing compile error:
```c++
[  7%] Building CXX object alignment/configuration/CMakeFiles/align_config_common_test.dir/align_config_common_test.cpp.o

/home/travis/build/seqan/seqan3/test/unit/alignment/configuration/align_config_common_test.cpp:21:10: fatal error: seqan3/alignment/configuration/align_config_vectorise.hpp: No such file or directory
   21 | #include <seqan3/alignment/configuration/align_config_vectorise.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

In test/unit/alignment/configuration/align_config_common_test.cpp

1) I added a fix for master that replaced all.hpp header with the explicit headers
2) release renamed one of those configurations
3) There was no merge-conflict, because both changes were orthogonal.

We can do 2 things:
1. backport my patch from master into release-3.0.2
2. create a merge-commit that fixes that single include

I would prefer 2.

**Comment by marehr** [comment]
Superseeded by #2043

**Comment by smehringer** [comment]
I have no experience with this so I don't have a preference :shrug:

**Pull request closed without merging**
