### PR TITLE
[FIX] Fixes missing aligned_alloc on mac os

### PR DESCRIPTION
**Pull request by rrahn**
On macos glibc does not implement aligned_alloc 😖 so we need to fallback to posix_memalign.

### CODE REVIEW

**Comment by h-2** [comment]
I assume this is the same as on FreeBSD and its just a bug in GCC7 (GCC8 should work) and it has been fixed already for GCC7.4 which will be released very soon.

**Comment by rrahn** [comment]
It does not seem to be a bug of gcc. It is a problem of the OS shipped glibc [see](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69680). And on mac os this is not available. Neither macports nor brew installed gcc support them. Note that I installed most recent libgcc version and tested with gcc8. I will install gcc9 as well and try it but I opened already a bug report to apple to see what they have to say.

**Comment by rrahn** [comment]
as expected a newer version of gcc does not fix the issue.

**Comment by h-2** [comment]
Hm, ok, just FYI, I was referring to this bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83662
I am pretty sure macOS uses the freebsd libc, but it might be outdated...

**Comment by h-2** [comment]
PS libc != libgcc

**Comment by rrahn** [comment]
```
==89923== LEAK SUMMARY:
==89923==    definitely lost: 0 bytes in 0 blocks
==89923==    indirectly lost: 0 bytes in 0 blocks
==89923==      possibly lost: 72 bytes in 3 blocks
==89923==    still reachable: 72,904 bytes in 7 blocks
==89923==         suppressed: 22,424 bytes in 153 blocks
==89923== Reachable blocks (those to which a pointer was found) are not shown.
==89923== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

Does not seem to leak.

**Comment by rrahn** [comment]
jenkins is not responding so I'll merge it now.

**Pull request merged**
