### PR TITLE
move travis from ubuntu14.04 to ubuntu16.04, add GCC8

### PR DESCRIPTION
**Pull request by h-2**
* switch from Ubuntu 14.0.4 to 16.04
* add a GCC8 test
* remove test of benchmark in debug

### CODE REVIEW

**Comment by marehr** [comment]
Is recently looked if travis has a new ubuntu version. And the most that I found is that it was still in beta and that it might not always work. Is there some announcement that made this official?

**Comment by h-2** [comment]
It's on the regular page: https://docs.travis-ci.com/user/reference/overview/

**Comment by marehr** [comment]
https://blog.travis-ci.com/2018-11-08-xenial-release

okay, because I looked into it two weeks ago.

**Comment by h-2** [comment]
They have also fixed long-standing issues with mac so we should be able to add mac, as well, but I wanted to get this in first to see if it resolves the issues with #535

**Comment by marehr** [comment]
And they have windows support :fearful: 

Let's merge :full_moon_with_face:

**Pull request merged**
