### PR TITLE
gcc8: fix declare_view_functor_type error

### PR DESCRIPTION
**Pull request by marehr**
this partially resolves (#261)

### CODE REVIEW

**Comment by marehr** [comment]
@h-2 Commenting this portion out works. The problem is that `declare_view_functor_type` can only take one type `view_type`, but you gave in a couple of types. So gcc-8 correctly rejects this code.

Was this an oversight or was it intended?

The thing I wonder is, that you could have used `declare_view_functor_type` directly but opted to use a new type `parent_type = declare_view_functor_type`. The name indicates that you want to convert something, but I'm not sure what you can do with the given types.

The PR is work-in-progress (comment will be removed after your go).

**Comment by h-2** [comment]
> @h-2 Commenting this portion out works. The problem is that declare_view_functor_type can only take one type view_type , but you gave in a couple of types. So gcc-8 correctly rejects this code.

I did not give multiple types, I gave one fully qualified type! `view_type` is a class template, not a type.
From my POV gcc8 wrongly rejects this and also wrongly accepts the new version.

> The thing I wonder is, that you could have used declare_view_functor_type directly but opted to use a new type parent_type = declare_view_functor_type . The name indicates that you want to convert something, but I'm not sure what you can do with the given types.

No, I am not converting, I am merely specifying the type fully. It could work to just use `declare_view_functor_type` since it is fully qualified at that point already. Maybe I thought it wouldn't work because it's a class template template? In any case a would prefer that as solution if it works.

**Comment by marehr** [comment]
@h-2 I'm slightly confused.

Can't I just write:

```c++
        template <typename urng_t, size_t... Is>
        auto explode(urng_t && urange, std::index_sequence<Is...> const &)
        {
            return view_type{std::forward<urng_t>(urange), std::forward<arg_types>(std::get<Is>(_arguments))...};
        }
```

instead of

```c++

        template <typename urng_t, size_t... Is>
        auto explode(urng_t && urange, std::index_sequence<Is...> const &)
        {
            return declare_view_functor_type{}(std::forward<urng_t>(urange), std::forward<arg_types>(std::get<Is>(_arguments))...);
        }
```
??

**Comment by marehr** [comment]
Why has `auxiliary_functor_t` the argument size requirement?

https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/detail.hpp#L164-L176

NOTE: the comment says **possible** arguments. Does this mean it allows also zero arguments?

Some callees don't assume a number of arguments:

https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/detail.hpp#L229-L233

This one does:

https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/detail.hpp#L276-L284

**Comment by rrahn** [comment]
@marehr this is a bit confusing but I try to lighten you up.
There are two possibilities with each distinguishing between `0` or ≥ `1` arguments:

scenario 1:
```cpp
auto v = my_view(std::vector<int>{0, 1, 2, 3});  // call creates a new view with pointing to the vector as underlying range.
auto v2 = my_view_2(std::vector<int>{0, 1, 2, 3}, foo, bar);  // call creates a new view with pointing to the vector as underlying range with some additional arguments to the view.
```

This is handled by:
https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/detail.hpp#L142-L149

which returns the actual view instance. 

scenario 2:
```cpp
auto v = std::vector<int>{0, 1, 2, 3} | my_view;  // call creates a new view with pointing to the vector as underlying range.
auto v2 = std::vector<int>{0, 1, 2, 3} | my_view_2(foo, bar);  // call creates a new view with pointing to the vector as underlying range with some additional arguments to the view.
```

Now, in the first call this pipe operator is used:
https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/detail.hpp#L322-L328

which simply takes the vector (urng) as lhs argument and the view_functor itself as the rhs argument.
In the second line, it get's tricky. We use https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/detail.hpp#L229-L233
to actually construct a proxy that holds the arguments passed to the actual view, and then have https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/detail.hpp#L276-L284
which constructs a new view given the proxy as rhs argument from the function call operator above.
So in this sense, the proxy should never be called with `0` arguments and I think an assertion would be more fitting then a constraint on the proxy operator.

However, this also forbids this:

```cpp
auto v = std::vector<int>{0, 1, 2, 3} | my_view(); 
```
which is a general weakness of this functor concept, as it actually is an invocable but one could easily mistake it as a class calling it's c'tor. So using `{}` does not work and it might be confusing to people.
But maybe this is just me, who still sometimes falls back in the pre-range c++ world.

Now, I think within the explode function of the proxy, we could directly return the constructed `view_type{...}` instead of creating an instance of the functor again and call it's operator. 
Second, I think the functor should be declared as:
```cpp
template <template <typename, typename ...> class view_type>
struct declare_view_functor_type
{
...
};
```
since we don't know, if the underlying view might need multiple template parameters.

**Comment by marehr** [comment]
Thank you for clearing this up. I was wondering about this case:
```cpp
auto v = std::vector<int>{0, 1, 2, 3} | my_view(); 
```

----

> Now, I think within the explode function of the proxy, we could directly return the constructed `view_type{...}` instead of creating an instance of the functor again and call it's operator. 
I still use the functor for DRY reasons

> Second, I think the functor should be declared as:
>
> ```cpp
> template <template <typename, typename ...> class view_type>
> struct declare_view_functor_type
> {
> ...
> };
> ```
> since we don't know, if the underlying view might need multiple template parameters.
@h-2 Do you agree?

**Comment by h-2** [comment]
> I still use the functor for DRY reasons

That was my reason, as well. It is good to have one point where you delegate to the type and not multiple.

> Second, I think the functor should be declared as:
>
> ```cpp
> template <template <typename, typename ...> class view_type>
> struct declare_view_functor_type
> {
> ...
> };
> ```
> since we don't know, if the underlying view might need multiple template parameters.

IIRC I had this at some point, but something didn't work. I think it is because `view_type` is actually not fully deduced and the functions would need to the second parameter pack, but they don't have it's name. This would only work if the template parameters where passed the functor explicitly (I remember having that, but it is more ugly).
[it works here without template arguments only because it relies on argument deduction guides in view_type]

In any case I can have a look at it again when I am back, but this is not related to the issue.

**Comment by rrahn** [comment]
>IIRC I had this at some point, but something didn't work. I think it is because view_type is actually not fully deduced and the functions would need to the second parameter pack, but they don't have it's name. This would only work if the template parameters where passed the functor explicitly (I remember having that, but it is more ugly).
[it works here without template arguments only because it relies on argument deduction guides in view_type]

Mhmm, I might not see the full problem but a simple demo on [godbolt](https://godbolt.org/g/o5mqZt) seems to indicate that this works without problems. Of course the underlying view must provide a way to deduce all template parameter from the ctor arguments. 
But anyway, this is another issue and not related to this.

**Comment by marehr** [comment]
!rebuild

**Comment by marehr** [comment]
I opened #272 for further discussion.

**Comment by marehr** [comment]
!rebuild

**Comment by marehr** [comment]
@rrahn are you merging? Jenkins died again :disappointed:

**Comment by rrahn** [comment]
!perf

**Comment by rrahn** [comment]
!perf

**Comment by rrahn** [comment]
Ok, it seems to work now.

**Comment by rrahn** [comment]
lgtm

**Comment by marehr** [comment]
nice! Merge?

**Pull request merged**
