### PR TITLE
Feature/align cfg edit

### PR DESCRIPTION
**Pull request by rrahn**
rebased on #441 and #440

### CODE REVIEW

**Comment by rrahn** [comment]
Superseded by #445 which fixes also this error.

**Comment by marehr** [comment]
Tests are failing:

```
/home/travis/build/seqan/seqan3/test/unit/alignment/configuration/align_config_edit_test.cpp: In member function ‘virtual void align_cfg_edit_is_global_Test::TestBody()’:
/home/travis/build/seqan/seqan3/test/unit/alignment/configuration/align_config_edit_test.cpp:43:13: error: ‘has_align_cfg_v’ is not a member of ‘seqan3::detail’
     EXPECT_TRUE((detail::has_align_cfg_v<align_cfg::id::global, decltype(align_cfg::edit)>));
             ^~~~~~~~~~~~~~~
```

**Comment by rrahn** [comment]
@marehr please see my comment above.
There is a utility function that was missing in this PR that is added in #445

**Comment by marehr** [comment]
ah lol; can be closed?

**Comment by rrahn** [comment]
If there are no issues to resolve? But I can fix them upstream in the other PR if so.

**Comment by rrahn** [comment]
superseded by #445

**Pull request closed without merging**
