### PR TITLE
[DOC] Release checklist: link to Debian package

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by eseiler** [comment]
Thanks, I added it to the current issue. We usually update the template with all the new points after release

**Review by eaasna — APPROVED** [review]
Hi @mr-c I approved the PR but could you please give a bit of insight to what this means i.e what your role as an upstream package maintainer is? :)

**Comment by mr-c** [comment]
> Hi @mr-c I approved the PR but could you please give a bit of insight to what this means i.e what your role as an upstream package maintainer is? :)

Thanks!

I'm a volunteer with the Debian project with the status of "Debian Developer". As part of the Debian Med team of volunteers I package seqan3 releases into a [Debian source package](https://packages.debian.org/source/sid/seqan3) that produces two Debian packages available for installation: [libseqan3-dev](https://packages.debian.org/sid/libseqan3-dev) and [seqan3-doc](seqan3-doc)

As part of the packaging we adapt the Seqan3 releases via [various patches](https://sources.debian.org/patches/seqan3/3.0.2+ds-8/); typically to use the Debian packages instead of bundled/download third-party code.

We also run the Seqan3 tests periodically. As errors/bugs appear due to new compiler versions or other changes in dependencies I triage those bugs and communicate them to the Seqan3 team here on GitHub. If a fix is developed I try add it to the Debian package.

**Review by smehringer — APPROVED** [review]

**Comment by eaasna** [comment]
> > Hi @mr-c I approved the PR but could you please give a bit of insight to what this means i.e what your role as an upstream package maintainer is? :)
> 
> Thanks!
> 
> I'm a volunteer with the Debian project with the status of "Debian Developer". As part of the Debian Med team of volunteers I package seqan3 releases into a [Debian source package](https://packages.debian.org/source/sid/seqan3) that produces two Debian packages available for installation: [libseqan3-dev](https://packages.debian.org/sid/libseqan3-dev) and [seqan3-doc](https://packages.debian.org/sid/seqan3-doc)
> 
> As part of the packaging we adapt the Seqan3 releases via [various patches](https://sources.debian.org/patches/seqan3/3.0.2+ds-8/); typically to use the Debian packages instead of bundled/download third-party code.
> 
> We also run the Seqan3 tests periodically. As errors/bugs appear due to new compiler versions or other changes in dependencies I triage those bugs and communicate them to the Seqan3 team here on GitHub. If a fix is developed I try add it to the Debian package.

Thank you for the explanation!

**Pull request merged**
