### PR TITLE
[Alignment Configuration] Enable free end gap config of method_global in policies.

### PR DESCRIPTION
**Pull request by smehringer**
Extracted from #2032 

Only the last commit is relevant

### CODE REVIEW

**Comment by marehr** [comment]
Can you help me?

* 1st commit is https://github.com/seqan/seqan3/pull/2045
* 2nd commit is ???? PR

**Review by marehr — APPROVED** [review]
Last commit looks fine :)

**Comment by marehr** [comment]
(Can you rebase and solve the merge-conflict?)

**Comment by smehringer** [comment]
Thanks for marking the PRs as blocked :+1:

**Review by eseiler — APPROVED** [review]

**Comment by smehringer** [comment]
Code coverage fail is unrelated

**Pull request merged**
