### PR TITLE
[INFRA] Exclude std and contrib from coverage tests

### LINKED ISSUE #697: Exclude std and contrib module from coverage

### PR DESCRIPTION
**Pull request by eseiler**
Resolves #697

### CODE REVIEW

**Comment by rrahn** [comment]
@h-2 this has nothing to do with the coverage tests. Every then and now, they are not passing because of timeouts. Triggering the build again mostly resolves this.

**Comment by h-2** [comment]
Put this PR does in fact touch coverage builds, that's why I'd like for the test to pass before merging it. Especially since the coverage test in Jenkins is fake (can you fix that with the other changes?).

**Comment by rrahn** [comment]
For sure, the test should go through. But I was just saying, that I experienced it to happen quite often lately. What do you mean with `is fake`?

**Comment by h-2** [comment]
It says it does coverage tests, but it doesn't.

I recommended @eseiler do a rebase so the coverage tests move up in priority, but that's not the problem here right now.

**Comment by rrahn** [comment]
Ah in Jenkins. 🤦‍♂️  Sorry I misread this. Yes, they will be added there as well. Maybe a better place for the coverage tests anyway.

**Comment by eseiler** [comment]
I rebased it.
I also noticed that sometimes the coverage tests time out and then just restart them.

**Pull request merged**
