### PR TITLE
[INFRA] Deactivate travis

### PR DESCRIPTION
**Pull request by eseiler**

### CODE REVIEW

**Comment by eseiler** [comment]
Jenkins fail unrelated (tests passed, upload failed). I restarted Jenkins.

**Review by MitraDarja — APPROVED** [review]

**Review by marehr — APPROVED** [review]

**Comment by marehr** [comment]
ccache does not seem to work :(

**Comment by eseiler** [comment]
> ccache does not seem to work :(
> 
> ```
> Cache not found for input keys: Snippet gcc7-ccache-2020-08-24-12;44;19, Snippet gcc7-ccache-.
> ```

May be that we didn;t have any caches yet.
Another PR:

```
Cache restored from key: Header gcc7-ccache-2020-08-24-12;41;51
```

**Comment by eseiler** [comment]
@marehr The jenkins macos nodes seem to be offline...; rest of the CI passed

**Pull request merged**
