### PR TITLE
supersedes [FIX] Implement the --copyright flag from @joshuak94

### PR DESCRIPTION
**Pull request by smehringer**
supersedes #688

### CODE REVIEW

**Comment by smehringer** [comment]
@h-2 All tests pass, can you review?

**Comment by h-2** [comment]
Both commits are now yours and not @joshuak94 's? I am fine with it, just saying...

**Comment by smehringer** [comment]
I had to change both, I don't know how I can keep Josh in the authorship?
... I know it's not ideal but we need this for the tutorials and he is not coming back before the PMSB :/

**Comment by smehringer** [comment]
There you go.

**Comment by h-2** [comment]
Has conflicts....

**Comment by smehringer** [comment]
@h-2 Conflicts resolved and tests pass

**Pull request merged**
