### PR TITLE
[MISC] Update align_cfg::output_score to recent config design changes.

### PR DESCRIPTION
**Pull request by rrahn**
part of seqan/product_backlog#217

### CODE REVIEW

**Review by eseiler — APPROVED** [review]

**Review by eseiler — CHANGES_REQUESTED** [review]
LGTM but you forgot the benchmarks/snippets

**Comment by eseiler** [comment]
I think you replaced `seqan3::align_cfg::output_score ` to `seqan3::align_cfg::output_score{} `? (Note the whitespace).
All errors I saw have `seqan3::align_cfg::output_score;` or `seqan3::align_cfg::output_score);`

**Comment by rrahn** [comment]
Yes, building it locally takes too long. So I use CI to run the tests for me. Always finding some file that I missed to update 😭

**Review by eseiler — APPROVED** [review]

**Review by smehringer — APPROVED** [review]

**Comment by smehringer** [comment]
needs a rebase :)

**Pull request merged**
