### PR TITLE
[feature] make alignment matrices printable

### LINKED ISSUE #510: deprecate matrix formatter for a direct debug_stream overload
As discussed in #495 we want to throw away the `matrix_formatter` and put the code directly into a `debug_stream` overload.

-----

### Preliminaries

We currently have 3 major ways to print matrices:
* ASCII
  ```c++
     | |A|A|C|C|G|G|T|T|
     /-/-/-/-/-/-/-/-/-/
     |0|1|2|3|4|5|6|7|8|
     /-/-/-/-/-/-/-/-/-/
    A|1|0|1|2|3|4|5|6|7|
     /-/-/-/-/-/-/-/-/-/
    C|2|1|1|1|2|3|4|5|6|
     /-/-/-/-/-/-/-/-/-/
    G|3|2|2|2|2|2|3|4|5|
     /-/-/-/-/-/-/-/-/-/
  ```
* CSV
  ```c++
     ; ;A;A;C;C;G;G;T;T;
     ;0;1;2;3;4;5;6;7;8;
    A;1;0;1;2;3;4;5;6;7;
    C;2;1;1;1;2;3;4;5;6;
    G;3;2;2;2;2;2;3;4;5;
    T;4;3;3;3;3;3;3;3;4;
  ```
* UNICODE
  ```c++
     ║ε║A║A║C║C║G║G║T║T║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    ε║0║1║2║3║4║5║6║7║8║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    A║1║0║1║2║3║4║5║6║7║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    C║2║1║1║1║2║3║4║5║6║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    G║3║2║2║2║2║2║3║4║5║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    T║4║3║3║3║3║3║3║3║4║
  ```

We will remove ASCII in favour of CSV, because CSV is generally more useful (e.g. put that into excel) and only support one UNICODE. We use `seqan3::fmtflags2` and `utf8` to distinguish whether to output CSV or UNICODE. 

### Introduce debug_matrix

We currently have alignment matrices, such as `alignment_score_matrix<>` and `alignment_trace_matrix<>`.
* CON: They don't store the sequences and thus can't print them, so output is only like
  ```c++
     ║ε║ ║ ║ ║ ║ ║ ║ ║ ║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    ε║0║1║2║3║4║5║6║7║8║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
     ║1║0║1║2║3║4║5║6║7║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
     ║2║1║1║1║2║3║4║5║6║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
     ║3║2║2║2║2║2║3║4║5║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
     ║4║3║3║3║3║3║3║3║4║
  ```

We will add a new matrix that will be called debug_matrix and which can store sequences and will take over the functionality of alignment_formatter in the debug_stream overload.

### PR DESCRIPTION
**Pull request by marehr**
Exposes alignment matrices as debug_stream printable.

It is still open, how to tackle #905.

resolves #510

### CODE REVIEW

**Comment by h-2** [comment]
I meant "deprecate matrix formatter for a direct debug_stream overload" in #510 more literally and you also wrote:
> As discussed in #495 we want to throw away the matrix_formatter and put the code directly into a debug_stream overload.

I think we should get rid of the formatter and the formats completely. Just have one debug_stream overload for the matrix type that has all the code inside. Possibly with an extra if check inside for utf8 vs ASCII, but that's it.

**Comment by marehr** [comment]
Okay, I talked this over with @rrahn. And we will remove the formatter in the future. I will update #510 to describe how to do this.

So let's see this PR as a stepping stone to get #510 done. The first milestone that we can now debug_stream alignment matrices will be done by this. The rest will follow.

**Comment by h-2** [comment]
This PR broke all nightlies on all platforms.

**Comment by marehr** [comment]
@h-2 This PR broke nothing it was a different one, but I already added a fix #926. Please review that.

**Pull request merged**
