### PR TITLE
[INFRA] Enable catalina g++-9 builds.

### PR DESCRIPTION
**Pull request by rrahn**
Blocked by #1362

### CODE REVIEW

**Comment by eseiler** [comment]
Either you downgrade to 9.1 or we re-discuss https://github.com/seqan/seqan3/issues/1220

**Comment by rrahn** [comment]
> Either you downgrade to 9.1 or we re-discuss #1220

Well, non of this will work with Xcode 11 due to the include error that I reported earlier. So for now we have to stick then to one mac machine which is ok for now I guess.

**Comment by rrahn** [comment]
@eseiler mit dem FIT für gcc9, this should now run through 🤞

**Comment by eseiler** [comment]
the `aligned_allocator_test` fails (throws `bad_alloc` sometimes)

**Comment by rrahn** [comment]
right... that was also breaking 🤦‍♂

**Pull request merged**
