### PR TITLE
Quality alphabet

### PR DESCRIPTION
**Pull request by mariehoffmann**
New version of the quality alphabet with 4 commits with most recent, required changes.

### CODE REVIEW

**Comment by h-2** [comment]
Is this work-in-progress or is this done from your POV / do you need another review?

**Comment by mariehoffmann** [comment]
Done from my POV.

**Comment by h-2** [comment]
@mariehoffmann I have re-opened this! Could you please rebase it to the current master branch, remove the internal_quality_alphabet_concept (all the other internal_concepts were removed over a year ago :wink) and clean up the commit history?
Then maybe we can get this merged this week, that would be awesome!

**Comment by h-2** [comment]
Oh, and I think the string literals are missing, they would be good to have, too

**Pull request closed without merging**
