### PR TITLE
[FIX] Change parentheses initialization to brace initialization for v…

### PR DESCRIPTION
**Pull request by joshuak94**
…arious snippet examples in the argument parser module.

### CODE REVIEW

**Comment by h-2** [comment]
Why was the second commit (explicit string) necessary?

**Comment by joshuak94** [comment]
There was a bug where parentheses works with the implicit string, but changing it to curly braces all of a sudden caused a run time error... I think @smehringer knows more?

**Comment by h-2** [comment]
@smehringer what's the problem here?

**Comment by joshuak94** [comment]
@smehringer is this still good to merge?

**Comment by smehringer** [comment]
I want to wait for the unit tests introduced in #848 so I can investigate why we need to construct explicitly from std::string for the file_ext_validator before we merge this PR.

**Comment by joshuak94** [comment]
So, brace initialization of something like the `file_ext_validator` without explicitly giving the file extensions as strings will cause a runtime error:
```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
[1]    17242 abort      argument_parser/validators_3_snippet
```

But with an explicit `std::string{}` call, or by using parenthesis initialization, there is no error. Any thoughts? @smehringer

**Comment by joshuak94** [comment]
Can I bump this? @smehringer :)

**Comment by h-2** [comment]
Snippet tests still fail.

**Comment by smehringer** [comment]
@joshuak94 Please remove the `file_ext_validator` initializer_list constructor. Then everything will work :)
We don't need it anyway, now that we have the extra "case sensitive* parameter

**Comment by joshuak94** [comment]
So then should I also remove the tests which use an initializer list?

**Comment by smehringer** [comment]
no, just leave everything as-is!
I'll explain:

With the extra `case_sensitive` parameter, the initializer list is obsolete, because an initializer list must contain values of the same type.
```cpp
file_ext_validator{"hi", "ho", true}; // never possible
file_ext_validator{"hi", "ho"}; // right now possible because of initializer list but weird ()  
file_ext_validator{{"hi", "ho"}, true}; // possible, but delegates to initializer list which tries to initialize a list of list of strings, which we do not want :(  
```
The good thing: The third one is also possible with the vector because the vector has an initializer list constructor :) so it will just work (worked on my branch :D).

**Pull request merged**
