### PR TITLE
[DOC] Updated dead links from .../iterator/... to .../range/...

### LINKED ISSUE #252: Update links in documentation to cppreference.com
A couple of links have moved and should be updated in the documentation, e.g. this url:

> http://en.cppreference.com/w/cpp/experimental/ranges/iterator/SizedRange

Source:
https://github.com/seqan/seqan3/blob/master/include/seqan3/range/concept.hpp#L63

### PR DESCRIPTION
**Pull request by joshuak94**
fixes #252

### CODE REVIEW

**Comment by h-2** [comment]
I'd like to not merge this right now, because #289 moves around some of the affected files and it is much easier to apply these changes after the other one has been merged (as opposed to the other way around).

**Comment by cpockrandt** [comment]
I think this can be merged now. I don't see any open PR that could interfere.

**Comment by marehr** [comment]
@joshuak94  Could you rebase? I think this should go in.

**Comment by joshuak94** [comment]
@h-2 @marehr Actually I think this can just be deleted now? The files no longer exist in the current master, and are now in std/iterator and std/ranges. But Hannes said that the links will be working once the ranges and such are fully implemented in C++? So should we just keep the dead links and wait for them to work?

**Comment by smehringer** [comment]
@marehr ping :stuck_out_tongue:

**Comment by smehringer** [comment]
sorry I keep pressing close and comment :woman_facepalming:

**Pull request closed without merging**
