### PR TITLE
Updated concept names

### PR DESCRIPTION
**Pull request by MitraDarja**
#520

I didn't change concepts which had a connection to std::range.

### CODE REVIEW

**Comment by marehr** [comment]
@h-2 We should review and merge this ASAP, because it touches ALOT.

**Comment by marehr** [comment]
@MitraDarja Could you make in the future a pull request which contains one change per commit? For example the renaming `aligned_sequence_concept` -> `AlignedSequenceRange` should have been one commit. That would be much easier for the reviewer to see what changed. It will also be easier to discuss naming issues.

@h-2 Do you think we should split this PR into multiple ones?

**Comment by h-2** [comment]
I had wanted to wait for this until after the alphabet refactorisation, because that also touches half of the library :see_no_evil:

**Comment by marehr** [comment]
Wuhu :trophy: :tada: major prs :grin:

**Comment by marehr** [comment]
@MitraDarja Could you write something how you inferred the name of the concepts and changed them? If it was tool generated, we might reapply it at a later point of time.

**Comment by MitraDarja** [comment]
I did it the real stupid way and used the find all and replace all function from atom to do this. But the list below should be an overview of all name changes. Names I didn't change are __cpp_concepts and sized_range_concept, because I was not sure to which name I should change it and for the second one there is also a concept like this in the std library?
Also, I didn't change all file names. So, there are a some files which have the word concept in it and in some test cases the word occurs as well. Do you want that changed as well? I think in the test cases it can actually be helpful to have the word concept remain in there.

``nucleotide_concept -> NucleotideAlphabet
aminoacid_concept -> AminoacidAlphabet
const_iterable_concept -> ConstIterableRange
floating_point_concept -> FloatingPoint
alphabet_concept -> Alphabet
constexpr_alphabet_concept -> constexpr_Alphabet
constexpr_semi_alphabet_concept -> constexpr_semi_Alphabet
cereal_output_archive_concept-> CerealOutputArchive
cereal_input_archive_concept -> CerealInputArchive
rna_structure_concept -> RnaStructure
char_adaption_concept -> CharAdaption
uint_adaption_concept -> UintAdaption
sequence_file_output_format_concept -> SequenceFileOutputFormat
alignment_file_output_format_concept -> AlignmentFileOutputFormat
structure_file_output_format_concept -> StructureFileOutputFormat
output_format_concept-> OutputFormat
sequence_file_InputFormat -> SequenceFileInputFormat
structure_file_InputFormat -> StructureFileInputFormat
input_format_concept-> InputFormat
deferred_config_element_concept -> DeferredConfigElement
simd_concept -> Simd
ostream_concept -> Ostream
istream_concept -> Istream
stream_concept -> Stream
sequence_container_concept -> SequenceContainerRange
random_access_container_concept -> RandomAccessContainerRange
reservable_container_concept -> ReservableContainerRange
container_concept -> ContainerRange
sdsl_index_concept -> SdslIndex
bi_fm_index_traits_concept -> BiFmIndexTraits
fm_index_traits_concept -> FmIndexTraits
bi_fm_index_concept -> BiFmIndex
fm_index_concept -> FmIndex
bi_fm_index_iterator_concept -> BiFmIndexIterator
fm_index_iterator_concept -> FmIndexIterator
aligned_sequence_concept -> AlignedSequenceRange
matrix_concept -> Matrix
arithmetic_concept -> Arithmetic
explicitly_convertible_to_concept -> ExplicitlyConvertibleTo
scoring_scheme_concept -> ScoringScheme
config_element_concept -> ConfigElement
implicitly_convertible_to -> ImplicitlyConvertibleTo
structure_file_input_traits_concept -> StructureFileInputTraits
convertible_to_concept -> ConvertibleTo
quality_concept -> Quality
type_list_of_structure_file_output_formats_concept -> TypeListOfStructureFileOutputFormats
type_list_of_structure_file_input_formats_concept -> TypeListOfStructureFileInputFormats
type_list_of_sequence_file_output_formats_concept ->
structure_file_format_concept -> StructureFileFormat
parse_condition_concept -> ParseCondition
sequence_file_format_out_concept -> SequenceFileFormatOut
tuple_like_concept -> TupleLike
sequence_file_format_concept -> SequenceFileFormat
fields_concept  -> Fields
sequence_file_input_traits_concept -> SequenceFileInputTraits
type_list_of_alignment_file_output_formats_concept -> TypeListOfAlignmentFileOutputFormats
alignment_file_format_concept -> AlignmentFileFormat
regular_invocable_concept
semi_global_config_concept -> SemiGlobalConfig
global_config_concept -> GlobalConfig
max_errors_concept -> MaxErrors
edit_distance_trait_concept  -> EditDistanceTrait
cereal_archive_concept -> CerealArchive
char_adaptation_concept -> CharAdaptation
uint_adaptation_concept -> UintAdaptation
weakly_ordered_with_concept -> WeaklyOrderedWith
implicitly_convertible_to_concept -> ImplicitlyConvertibleTo
is_assignable_concept  -> IsAssignable
weakly_equality_comparable_by_members_with_concept -> WeaklyEqualityComparableByMembersWith
weakly_ordered_by_members_with_concept -> WeaklyOrderedByMembersWith
standard_layout_concept -> StandardLayout
trivial_concept -> Trivial
validator_concept -> Validator
cerealisable_concept -> Cerealisable
trivially_destructible_concept -> TriviallyDestructible
trivially_copyable_concept -> TriviallyCopyable
tuple_size_concept -> TupleSize
tuple_get_concept -> TupleGet
compatible_concept -> Compatible
predicate_concept -> Predicate

**Comment by h-2** [comment]
This is superseded by other PRs.

**Pull request closed without merging**
