### PR TITLE
[FIX] properly guard ZLIB and BZIP2 

### PR DESCRIPTION
**Pull request by marehr**
In https://github.com/seqan/seqan3/issues/2726#issuecomment-856603031 we noticed that the current header tests can't be build via

```
cmake -DSEQAN3_NO_ZLIB=1 -DSEQAN3_NO_BZIP2=1 <seqan3>/test/header
```

This PR fixes that.

### CODE REVIEW

**Comment by eseiler** [comment]
What's the effect of `#if SEQAN3_HAS_ZLIB` -> `#if defined(SEQAN3_HAS_ZLIB)`?

`#ifdef SEQAN3_HAS_ZLIB` and `#if defined(SEQAN3_HAS_ZLIB)` are the same, we use both versions in the lib, so why was this changed? Just style?

**Comment by marehr** [comment]
> What's the effect of `#if SEQAN3_HAS_ZLIB` -> `#if defined(SEQAN3_HAS_ZLIB)`?
> 
> `#ifdef SEQAN3_HAS_ZLIB` and `#if defined(SEQAN3_HAS_ZLIB)` are the same, we use both versions in the lib, so why was this changed? Just style?

No particular reason, it was just easier to normalise `#if SEQAN3_HAS_ZLIB` and `#ifdef SEQAN3_HAS_ZLIB` to `#if defined(SEQAN3_HAS_ZLIB)` by a simple search and replace.

**Review by simonsasse — APPROVED** [review]
looks good. :)

**Review by eseiler — APPROVED** [review]

**Comment by eseiler** [comment]
rebase?

**Comment by marehr** [comment]
> rebase?

I didn't as the first commit is the exact same commit.

**Comment by eseiler** [comment]
I just noticed now that this had master as base, so this needs to be cherry-picked into release?

**Comment by marehr** [comment]
dammit

**Pull request merged**
