### PR TITLE
[FIX] simplify std::ranges::enable_view overloads

### PR DESCRIPTION
**Pull request by marehr**
A change in https://github.com/ericniebler/range-v3/pull/1455 simplified
the heuristics for std::ranges::enable_view. So the gap_decorator is by
default now no view anymore.

This PR is also in line with #1678 to remove dependencies of our library
in the std headers.

---

old description

I know that this introduces a macro (SEQAN3_STD_RANGES_NAMESPACE), but
this reduces code bloat for a feature that is only used for a single
data structure right now.

This PR is also in line with #1678 to remove dependencies of our library
in the std headers.

### CODE REVIEW

**Comment by h-2** [comment]
I managed to get the weird heuristics out of the standard so none of this code is required anymore. Changes to range-v3 were committed a couple of days ago so you could remove the code after upgrading: 
https://github.com/ericniebler/range-v3/pull/1455

**Comment by marehr** [comment]
@h-2 Okay, does that change any impact on our other views? Or do they all inherit from `std::ranges::view_interface`?

**Comment by h-2** [comment]
All our views inherit `std::ranges::view_interface` or `std::ranges::view_base` if I am not mistaken.

**Comment by rrahn** [comment]
> I managed to get the weird heuristics out of the standard so none of this code is required anymore. 

Ah that is good!

**Pull request merged**
