### PR TITLE
[NOP] Version bump 3.0.1

### PR DESCRIPTION
**Pull request by smehringer**
Version bump that should have followed the 3.0.0 release

blocked by #1507

### CODE REVIEW

**Comment by marehr** [comment]
:cry:

**Comment by marehr** [comment]
We have to make the version in the documentation visible.

The documentation is not distinguishable from
* https://docs.seqan.de/seqan/3.0.0/ and
* https://docs.seqan.de/seqan/3.0.1/

Should I open an issue for this or just make a Card?

**Comment by smehringer** [comment]
How do you want to do this?

**Comment by rrahn** [comment]
We would need a mechanism to switch between versions like we had for SeqAn. Is that something doxygen might support?

**Comment by h-2** [comment]
The SeqAn2 mechanism is just a small javascript thing that JongKyu wrote. It can probably be added easily to Doxygen, too.

**Pull request merged**
