### PR TITLE
[INFRA] Only run macOS CI if linux CI was successful

### PR DESCRIPTION
**Pull request by eseiler**
Blocked by https://github.com/seqan/seqan3/pull/2270

### CODE REVIEW

**Comment by marehr** [comment]
Can we somehow deduplicate it?

**Comment by eseiler** [comment]
> Can we somehow deduplicate it?

Looking at it, https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action seems promising.

**Comment by eseiler** [comment]
This works as intended, but there (currently) is no way to avoid the code duplication

**Comment by eseiler** [comment]
I'll reevaluate this once we can avoid the code duplication

**Pull request closed without merging**
