### PR TITLE
Use whole lemon repository

### PR DESCRIPTION
**Pull request by joergi-w**
Updates lemon submodule and makes use of the complete lemon repository instead of headers only. Allows us to run lemon tests in our lemon fork.

### CODE REVIEW

**Comment by h-2** [comment]
What? Wait! We discussed that we are not forking lemon. And also that because we are not forking it, we don't need to run it's tests. Why/when was this changed?

**Comment by marehr** [comment]
The problem is that the library has some `-Wextra` warnings that I found and must be fixed. It is easier to maintain this on a full fork of the library.

My suggestion was to make a full fork to maintain our patches. We should submit those patches to upstream and synchronize in the future. This is easier with a full fork.

**Comment by h-2** [comment]
Please don't just change infrastructure decisions like this. @rrahn and I discussed this with @joergi-w for hours and we decided to not do a fork. The whole decision of using Lemon and not something else was (also) based on the fact that we don't have to maintain a fork. The basis for including this as a submodule was that it is not 30MB big. 

@joergi-w said that the library produces no warnings and this was also a reason for choosing it over other libraries. If it is actually not true, and we can't use it without maintaining a fork and pulling in a repository that is 10x as big as ours, than we need to re-evaluate whether we can use Lemon at all.

**Comment by marehr** [comment]
```
> /lemon (git)-[master] % du -hs .
4.8M	.
```
Where is this big? And `-Wextra` always introduces new checks. It is impossible to stay safe from warnings for all time. And the only warning right now is the following:

```
/home/marehr/develope/seqan3/test/../lemon/include/lemon/greedy_tsp.h:249:2: warning: extra ‘;’ [-Wpedantic]
 }; // namespace lemon
  ^
```

As far as Jörg told me is lemon actively maintained, just that they had no issues in some years. I think if we create an issues it will be fixed eventually. We have this problem with every external library.

**Comment by h-2** [comment]
@marehr We discussed extensively, and there was broad consensus on not forking it. You were not part of this discussion so you can't know, but please accept that this was already discussed with multiple people.
@joergi-w said the library can be used as-is and if not, that's a problem. @joergi-w, you need to find out with upstream:
1. how fast they can fix the warnings; and
2. whether they can add modern compilers and our warning levels to their test system to prevent further warnings; and
3. whether they will produce a release within the next six months including fixes so that it is in time for the first SeqAn3 release.

If they agree to do this we can quickly switch to to their master branch. If not, we need to consider alternatives. This is a requirement for being able to use the library as we cannot and won't ship our own forks of dependencies.

**Comment by marehr** [comment]
@h-2, @rrahn, @joergi-w I don't want to overrule your decision in any way. 

I just found something that would have happened in the future anyway. And it is a perfect opportunity to test out how to handle this situation. I find your suggestion/procedure extremely good.

And to be fair, this particular warning is in general of no concern for us, because it is in code that we don't use. And it is a minor issue altogether. The code quality of lemon is indeed high and there is no reason to say no this fast.

**Comment by joergi-w** [comment]
@h-2 you are right. We discussed this deeply and it was a good decision to include the headers only and use the library as-is. I'm sorry that I got convinced too fast and I assumed wrongly that @marehr and you had discussed this and had come to the conclusion to change this. 

As I am responsible that the Lemon library satisfies our requirements and I am sure I want to keep using it, I will realize the following steps:
- [ ] close this PR without merge
- [ ] remove the branch with full library from our Lemon repository (keep header-only branch)
- [ ] compile the Lemon headers with high warning level again to check if there are more issues
- [ ] fix the ';' warning and send a PR to the Lemon developers
- [ ] ask the Lemon developers to perform tests with modern compilers and high warning levels

**Pull request closed without merging**
