### PR TITLE
[DOC] fix typos tutorial

### PR DESCRIPTION
**Pull request by wvandertoorn**
Came across two small typos.

### CODE REVIEW

**Comment by wvandertoorn** [comment]
@smehringer requesting your review directly because I think this does not need two reviews

**Comment by smehringer** [comment]
We actually require 2 reviews by the Github policy :sweat_smile: so "merging is blocked".

**Comment by smehringer** [comment]
@marehr please merge once you approve :)

**Comment by wvandertoorn** [comment]
Oh, woops.   :sweat_smile:

**Pull request merged**
